CREATE OR REPLACE TABLE FACT_REVENUE(
    REVENUE_ID INT PRIMARY KEY,
    USER_ID INT  NOT NULL,
    WALLET_ID INT,
    REVENUE_TYPE_ID INT NOT NULL,
    REVENUE_AMOUNT DECIMAL(18,2) NOT NULL,
    SOURCE_TRANSACTION_ID INT NOT NULL,
    REVENUE_TIMESTAMP TIMESTAMP NOT NULL,
    REVENUE_DATE_ID INT NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES DIM_USER(USER_ID),
    FOREIGN KEY(WALLET_ID) REFERENCES DIM_WALLET(WALLET_ID),
    FOREIGN KEY(REVENUE_DATE_ID) REFERENCES DIM_DATE(DATE_ID),
    FOREIGN KEY(SOURCE_TRANSACTION_ID) REFERENCES FACT_TRANSACTION(TRANSACTION_ID),
    FOREIGN KEY(REVENUE_TYPE_ID) REFERENCES DIM_REVENUE_TYPE(REVENUE_TYPE_ID)
);