CREATE OR REPLACE TABLE dim_user(
    user_id BIGINT,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    country VARCHAR(50),
    region VARCHAR(50),
    city VARCHAR(50),
    email_address VARCHAR(255),
    reported_annual_income DECIMAL(18,2),
    acquisition_channel VARCHAR(20),
    customer_persona VARCHAR(20),
    kyc_completed BOOLEAN,
    date_of_birth DATE,
    birth_date_id INT,
    signup_date TIMESTAMP,
    signup_date_id INT,
    is_activated_user BOOLEAN,
    wallet_activation_timeframe INT,
    customer_behaviour_segment VARCHAR(50)
)