CREATE OR REPLACE TABLE dim_user(
    user_id INT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    country VARCHAR(50),
    region VARCHAR(50),
    city VARCHAR(50),
    email_address VARCHAR(255) UNIQUE NOT NULL,
    reported_annual_income DECIMAL(18,2),
    acquisition_channel VARCHAR(20),
    customer_persona VARCHAR(20),
    kyc_completed BOOLEAN NOT NULL,
    date_of_birth DATE,
    birth_date_id INT,
    signup_date TIMESTAMP NOT NULL,
    signup_date_id INT,
    is_activated_user BOOLEAN,
    wallet_activation_timeframe INT,
    ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)